# Arrays

In [1]:
# Column Vector
array1 = [1, 2, 3]
typeof(array1)

Array{Int64,1}

In [2]:
# Row Vector
array2 = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [3]:
transpose(array1)

1×3 LinearAlgebra.Transpose{Int64,Array{Int64,1}}:
 1  2  3

In [4]:
# With a mix of types, all the elements inherit the "highest" type
array3 = [1, 2, 3.0]
typeof(array2)

Array{Int64,2}

In [5]:
# Column-wise entry of multidimensional array
array4= [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [6]:
# Row-wise entry of multidimensional array
array5 = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [7]:
# The length() function returns the number of elements.
length(array4), length(array5)

(9, 9)

In [8]:
# Indexes of Elements above

# Index order of column-wise array
for i in 1:length(array4)
    println("Element $(i) is ", array4[i])
end

# Index order of row-wise array
for i in 1:length(array5)
    println("Element $(i) is ", array5[i])
end

Element 1 is 1
Element 2 is 2
Element 3 is 3
Element 4 is 4
Element 5 is 5
Element 6 is 6
Element 7 is 7
Element 8 is 8
Element 9 is 9
Element 1 is 1
Element 2 is 4
Element 3 is 7
Element 4 is 2
Element 5 is 5
Element 6 is 8
Element 7 is 3
Element 8 is 6
Element 9 is 9


In [9]:
# Using repeat() to repeat column elements
repeat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [10]:
# Using repeat() to repeat row elements
repeat([1 2], 3)

3×2 Array{Int64,2}:
 1  2
 1  2
 1  2

In [11]:
# Using range(start, step, number of elements)
range(1, step = 1, length = 10)

1:1:10

In [12]:
# Create collections using the collect() function
collect(range(1, step = 1, length = 10))

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [13]:
# Same
collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [14]:
# Creating empty array with two rows and three columns
array6 = Array{Union{Missing, Int}}(missing, 2, 3)

2×3 Array{Union{Missing, Int64},2}:
 missing  missing  missing
 missing  missing  missing

In [15]:
# Reshaping
reshape(array6, 3, 2)

3×2 reshape(::Array{Union{Missing, Int64},2}, 3, 2) with eltype Union{Missing, Int64}:
 missing  missing
 missing  missing
 missing  missing

In [16]:
# Creating a 10 x 5 array with each element drawn randomly from value 10 through 20
array7 = rand(10:20, 10, 5)

10×5 Array{Int64,2}:
 15  15  19  15  18
 10  15  17  18  16
 17  19  13  17  10
 17  11  10  20  16
 11  19  13  17  17
 10  15  16  17  19
 17  20  19  11  17
 10  10  11  10  19
 20  15  12  20  18
 17  14  17  17  19

In [17]:
# All rows in first column
array7[:, 1]

10-element Array{Int64,1}:
 15
 10
 17
 17
 11
 10
 17
 10
 20
 17

In [18]:
# Rows two through five of second column
array7[2:5, 2]

4-element Array{Int64,1}:
 15
 19
 11
 19

In [19]:
# Values in rows 2, 4, 6, and in columns 1 and 5
array7[2, 4, 6], [1, 5]]

LoadError: syntax: extra token "]" after end of expression

In [20]:
# Values in row 1 from column 3 to the last column
array7[1, 3:end]

3-element Array{Int64,1}:
 19
 15
 18

In [21]:
# Boolean logic (returning only true or false)
array7[:, 1] .> 12

10-element BitArray{1}:
 1
 0
 1
 1
 0
 0
 1
 0
 1
 1

In [22]:
# We can add values to an array using the push!() function. Many functions in Julia have an added exclamation mark, called a bang. 
# It is used to make permanent changes to the values in a computer variable.

In [23]:
# Creating a five element array
array8 = [1, 2, 3, 4, 5]
# Permanantly append 10 to end of array
push!(array8, 10)

6-element Array{Int64,1}:
  1
  2
  3
  4
  5
 10

In [24]:
# The pop!() function removes the last element (the bang makes it permanent).
pop!(array8)

10

In [25]:
pop!(array8)
array8

4-element Array{Int64,1}:
 1
 2
 3
 4

In [26]:
# An example of list comprehension
array9= [3 * i for i in 1:5]

5-element Array{Int64,1}:
  3
  6
  9
 12
 15

In [27]:
# Column-wise collection iterating through second element first
array10 = [a * b for a in 1:3, b in 1:3]

3×3 Array{Int64,2}:
 1  2  3
 2  4  6
 3  6  9

In [28]:
# Elementwise addition of a scalar using dot notation
array10 .+ 1

3×3 Array{Int64,2}:
 2  3   4
 3  5   7
 4  7  10

In [29]:
# Missing is a Julia data type that provides a placeholder for missing data in a statistical sense. 
# It propagates automatically and its equality as a type can be tested. 
# Sorting is possible since missing is seen as greater than other values.

In [30]:
missing + 1

missing

In [31]:
missing > 1

missing

In [32]:
[1, 2, 3, missing, 5] + [10, 20, 30, 40 ,50]

5-element Array{Union{Missing, Int64},1}:
 11
 22
 33
   missing
 55

In [33]:
# Checking equality of value using ==
# Cannot return true or false since value is not known
missing == missing

missing

In [34]:
# Checking equality of type with ===
missing === missing

true

In [35]:
# Checking type equality with isequal()
isequal(missing, missing)

true

In [36]:
# Sorting with isless()
isless(1, missing)

true

In [37]:
# Checking on infinity
isless(Inf, missing)

true

In [38]:
# A 3 x 3 array of integer zeros
array11 = zeros(Int8, 3, 3)

3×3 Array{Int8,2}:
 0  0  0
 0  0  0
 0  0  0

In [39]:
# A 3 x 3 array of floating point ones
array12 = ones(Float16, 3, 3)

3×3 Array{Float16,2}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [40]:
# Fill an array with elements of value x
array14 = fill(10, 3, 3)

3×3 Array{Int64,2}:
 10  10  10
 10  10  10
 10  10  10

In [41]:
# Convert elements to a different data type
convert.(Float16, array14)

3×3 Array{Float16,2}:
 10.0  10.0  10.0
 10.0  10.0  10.0
 10.0  10.0  10.0

In [42]:
# Concatenate arrays along rows (makes rows)
array15 = [1, 2, 3]
array16 = [10, 20, 30]
cat(array15, array16, dims = 1)

6-element Array{Int64,1}:
  1
  2
  3
 10
 20
 30

In [43]:
# Concatenate along vertical axis, (rows)
vcat(array15, array16)

6-element Array{Int64,1}:
  1
  2
  3
 10
 20
 30

In [44]:
# Concatenate arrays along columns (makes columns)
cat(array15, array16, dims = 2)

3×2 Array{Int64,2}:
 1  10
 2  20
 3  30

In [45]:
# Concatenate along horizontal axis, (columns)
hcat(array15, array16)

3×2 Array{Int64,2}:
 1  10
 2  20
 3  30

# Tuples

Tuples are immutable collections. Immutable refers to the fact that the values are set and cannot be changed. This type is indicated by the use of parenthesis instead of square brackets.

In [46]:
tuple1 = (1, 2., π, 4, "Julia")

(1, 2.0, π, 4, "Julia")

In [47]:
for i in 1:length(tuple1)
    println(" The value of the tuple at index number $(i) is $(tuple1[i]) and the type is $(typeof(tuple1[i])).")
end

 The value of the tuple at index number 1 is 1 and the type is Int64.
 The value of the tuple at index number 2 is 2.0 and the type is Float64.
 The value of the tuple at index number 3 is π and the type is Irrational{:π}.
 The value of the tuple at index number 4 is 4 and the type is Int64.
 The value of the tuple at index number 5 is Julia and the type is String.


In [48]:
a, b, c, seven = (1, 3, 5, 7)
a, seven

(1, 7)

In [49]:
# Reverse order index (can be done with arrays too)
tuple1[end:-1:1]

("Julia", 4, π, 2.0, 1)

In [50]:
# Mixed length tuples
tuple2 = ((1, 2, 3), 1, 2, (3, 100, 1))

((1, 2, 3), 1, 2, (3, 100, 1))

In [51]:
# Element 2 in element 4
tuple2[4][2]

100